### ISSUE TITLE
multi-line comments are truncated

### ISSUE THREAD

**Issue by jbphet** [phetsims/slater#5]
In the course of the review of the States of Matter simulation I saw several instances of truncated multi-line comments in the JavaScript code.  It appears that this was a result of the comments not being moved over from the Java version of the code when slater was used.  

For example, there is a section of the code in DiatomicVerletAlgorithm.java that looks like this:

```java
            calculateWallForce( moleculeCenterOfMassPositions[i], normalizedContainerWidth, normalizedContainerHeight,
                                nextMoleculeForces[i] );

            // Accumulate this force value as part of the pressure being
            // exerted on the walls of the container.
            if ( nextMoleculeForces[i].getY() < 0 ) {
                pressureZoneWallForce += -nextMoleculeForces[i].getY();
            }
```

and was translated as this:

```js
        calculateWallForce( moleculeCenterOfMassPositions[i], normalizedContainerWidth, normalizedContainerHeight, nextMoleculeForces[i] );
        // exerted on the walls of the container.
        if ( nextMoleculeForces[i].getY() < 0 ) {
          pressureZoneWallForce += -nextMoleculeForces[i].getY();
        }
```

**Comment by jbphet** [comment]
Link to the related ticket in SOM: https://github.com/phetsims/states-of-matter/issues/89

**Comment by samreid** [comment]
Slater is deprecated, we will not be maintaining it.
